version: '3.8'

services:
  nodejs:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  flutter:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
