version: '3.8'

services:
  nodejs:
    image: jangleparth/todo-backend:latest
    
    ports:
      - "3000:3000"
    networks:
      - app-network

  flutter:
    image: jangleparth/todo-frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
